---
- name: install gpg
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - pinentry-mac
    - gnupg2
  when: ansible_distribution == 'MacOSX'
  tags:
    - packages
    - gnupg

- name: install gpg
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_os_family == 'Debian'
  become: yes
  with_items:
    - pcsc-tools
    - pcscd
    - scdaemon
    - gpg-agent
    - gnupg
  tags:
    - packages
    - gnupg

- name: create gnupg config directory
  file:
    dest: "{{ ansible_env.HOME }}/.gnupg"
    state: directory
  tags:
    - gnupg
    - gpg
    - gpg2
    - conf

- name: gpg-agent.conf
  template:
    dest: "{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf"
    src: gpg-agent.conf.j2
  tags:
    - gnupg
    - gpg
    - gpg2
    - conf

- name: gpg.conf
  template:
    dest: "{{ ansible_env.HOME }}/.gnupg/gpg.conf"
    src: gpg.conf.j2
  tags:
    - gnupg
    - gpg
    - gpg2
    - conf

- name: dirmngr.conf
  template:
    dest: "{{ ansible_env.HOME }}/.gnupg/dirmngr.conf"
    src: dirmngr.conf.j2
  tags:
    - gnupg
    - gpg
    - gpg2
    - conf

