---
- name: create global git config directory
  file: dest="{{ ansible_env.HOME }}/.config/git" state=directory

- name: create global git ignore file
  copy: src=gitignore dest="{{ ansible_env.HOME }}/.config/git/ignore" force=yes backup=no

- name: create global git attributes file
  copy: src=gitattributes dest="{{ ansible_env.HOME }}/.config/git/attributes" force=yes backup=no

- name: global git config file exists
  copy: content= dest="{{ ansible_env.HOME }}/.config/git/config" backup=yes force=no

- name: git config core.editor
  command: git config --global core.editor vim

- name: git config core.autocrlf
  command: git config --global core.autocrlf false

- name: git config color.ui
  command: git config --global color.ui auto

- name: git config alias.doglog
  command: git config --global alias.doglog 'log --decorate --oneline --graph'

- name: git config alias.serve
  command: git config --global alias.serve 'daemon --reuseaddr --verbose --base-path=. --export-all ./.git'

- name: git config alias.pr (thanks @jfrazelle!)
  raw: git config --global alias.pr '!pr() { git fetch origin pull/$1/head:pr-$1; git checkout pr-$1; }; pr'

- name: git config apply.whitepace
  command: git config --global apply.whitespace fix

  # Make git rebase work correctly on OSX. Thanks @jfrazelle and https://www.git-tower.com/blog/make-git-rebase-safe-on-osx
- name: git config core.trustctime
  command: git config --global core.trustctime false
  when: ansible_distribution == 'MacOSX'

- name: git config credential.helper
  command: git config --global credential.helper cache

- name: git config http.cookiefile
  command: git config --global http.cookiefile ~/.cache/git/cookies

- name: git config merge.tool
  command: git config --global merge.tool opendiff

- name: git config pull.rebase
  command: git config --global pull.rebase preserve

- name: git config push.default
  command: git config --global push.default simple

- name: unset multi-value git config value, url.git@github.com:.insteadOf
  command: git config --global --unset-all url.git@github.com:.insteadOf 
  ignore_errors: yes # ignore any errors; when the option doesn't exist, git-config returns an error.

- name: git config url insteadOf git://github.com/
  command: git config --global --add url.git@github.com:.insteadOf "{{ item }}"
  with_items:
    - git://github.com/
    - "github:"
    - https://github.com/

- name: git config web.browser
  command: git config --global web.browser open
  when: ansible_os_family == "Darwin"

- name: git config tag.sort
  command: git config --global tag.sort version:refname

- name: git config version.prereleaseSuffix -alpha
  command: git config --global version.prereleaseSuffix -alpha
- name: git config version.prereleaseSuffix -beta
  command: git config --global version.prereleaseSuffix -beta
- name: git config version.prereleaseSuffix -rc
  command: git config --global version.prereleaseSuffix -rc

- name: git config gpg.program gpg2
  command: git config --global gpg.program gpg2

- name: create $HOME/bin directory
  file: dest="{{ ansible_env.HOME }}/bin" state=directory

- name: create $HOME/bin/vault-diff.sh
  copy: src=vault-diff.sh dest="{{ ansible_env.HOME }}/bin/vault-diff.sh" force=yes backup=no

- name: git config diff.vault.command
  command: git config --global diff.vault.command vault-diff.sh
