---
- name: check golang
  shell: command -v go
  environment:
    PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
  ignore_errors: yes
  register: golang_check

- name: golang version check
  command: go version
  environment:
    PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
  when: golang_check.rc == 0
  register: installed_golang_version

- include_tasks: install-go.yml
  when: golang_check.rc != 0 or installed_golang_version.stdout.find('go version go' + golang_version) != 0
