---
- name: download go{{ golang_version }} archive
  get_url:
    url: https://go.dev/dl/{{ golang_pkg }}
    checksum: "{{ golang_checksums[ansible_architecture][ansible_system] }}"
    dest: /tmp/{{ golang_pkg }}
    timeout: 600

- name: remove go
  file:
    path: /usr/local/go
    state: absent
  become: yes

- name: unpack go{{ golang_version }} archive
  unarchive:
    src: /tmp/{{ golang_pkg }}
    dest: /usr/local
    copy: no
  become: yes

- name: build go toolchain
  command: go install std
  environment:
    GOOS: "{{ item | lower }}"
    GOARCH: amd64
    PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
  with_items:
    - Linux
    - Darwin
  when: ansible_system != item
  become: yes

- name: remove go archive
  file:
    path: /tmp/{{ golang_pkg }}
    state: absent
