---
- name: download protoc {{ protoc_version }} archive
  get_url: url=https://github.com/google/protobuf/releases/download/v{{ protoc_version }}/{{ protoc_pkg }}
            sha256sum={{ protoc_checksums[ansible_os_family] }}
            dest=/tmp/{{ protoc_pkg }}
            timeout=600

- name: unpack protoc {{ protoc_version }} archive
  unarchive: src=/tmp/{{ protoc_pkg }} dest=/usr/local copy=no
  become: yes

- name: remove protoc archive
  file: path=/tmp/{{ protoc_pkg }} state=absent
