---
- name: install packages
  homebrew: name={{ item }} state=latest
  with_items:
    - vim
    - python
    - git
    - mercurial
    - boot2docker
    - docker-machine
    - docker-compose
    - nodejs
    - dash
    - tmux
    - reattach-to-user-namespace
    - jq
  when: ansible_distribution == 'MacOSX'

- name: global npm packages
  npm: name={{ item }} global=true production=true state=latest
  with_items:
    - coffee-script
    - bower
    - grunt-cli

- name: install pip packages
  pip: name={{ item }} state=latest
  with_items:
    - awscli

- name: tmux-config
  copy: dest=~/.tmux.conf src=tmux.conf backup=yes

- name: tmux-osx.conf
  copy: dest=~/.tmux-osx.conf src=tmux-osx.conf backup=yes
  when: ansible_distribution == 'MacOSX'

- name: bashrc
  copy: dest=~/.bashrc src=bashrc backup=yes

- name: bashrc-osx
  copy: dest=~/.bashrc-osx src=bashrc-osx backup=yes
  when: ansible_distribution == 'MacOSX'

- name: bash_profile
  copy: dest=~/.bash_profile src=bash_profile backup=yes

# https://docs.python.org/2/library/site.html
- name: python site-packages configuration
  copy: dest=~/Library/Python/2.7/lib/python/site-packages/homebrew.pth src=homebrew.pth
  when: ansible_distribution == 'MacOSX'

- name: git doglog alias
  command: git config --global alias.doglog 'log --decorate --oneline --graph'

- name: git config serve alias
  command: git config --global alias.serve 'daemon --reuseaddr --verbose --base-path=. --export-all ./.git'

- name: git config core.excludesfile
  command: git config --global core.excludesfile "~/.gitignore"

- name: git config core.editor
  command: git config --global core.editor vim

- name: git config color.ui
  command: git config --global color.ui auto

- name: git config insteadOf https://github.com/
  command: git config --global url.git@github.com:.insteadOf https://github.com/

- name: git config push.default
  command: git config --global push.default simple

# pip install awscli
# git
# mercurial
# nodejs
# boot2docker
# bower
# git config core.excludesfile
# git core.excludesfile
# ~/.bashrc
# ~/.bash_profile

# nginx --with-debug
# virtualbox
# docker
# ~/.gitignore
# sourcetree
# colloquy
# hipchat
# go
# cross compile go for linux, darwin, and windows
# chrome
# firefox
# firebug
# balsamiq
# IntelliJ
# iTerm2
