---
- include: packages_{{ ansible_os_family }}.yml
  tags: packages

- name: global npm packages
  npm: name="{{ item }}" global=true production=true state=latest
  with_items:
    - coffee-script
    - bower
    - grunt-cli
  become: "{{ npm_become }}"
  tags:
    - packages

- name: install pip packages
  pip: name="{{ item }}" state=latest extra_args=--user
  with_items:
    - awscli
  become: "{{ pip_become }}"
  tags:
    - packages
    - python

- name: create $HOME bin directory
  file: dest="{{ ansible_env.HOME }}/bin" state=directory
  tags:
    - packages

- name: install $HOME/bin/color-test
  copy: dest="{{ ansible_env.HOME }}/bin/color-test" src=color-test backup=no mode=0755
  tags:
    - packages
    - homebin
    - bin

- name: install $HOME/bin/color-gradient
  copy: dest="{{ ansible_env.HOME }}/bin/color-gradient" src=color-gradient backup=no mode=0755
  tags:
    - packages
    - homebin
    - bin

- name: create tmux config directory
  file: dest="{{ ansible_env.HOME }}/.config/tmux" state=directory
  tags:
    - conf

- name: tmux.conf
  copy: dest="{{ ansible_env.HOME }}/.tmux.conf" src=tmux.conf backup=yes
  tags:
    - conf

- name: tmux config files
  copy: dest="{{ ansible_env.HOME }}/.config/tmux" src=tmux/ backup=yes
  tags:
    - conf

- name: create bash config directory
  file: dest="{{ ansible_env.HOME }}/.config/bash" state=directory
  tags:
    - conf

- name: bashrc
  copy: dest="{{ ansible_env.HOME }}/.bashrc" src=bashrc backup=yes
  tags:
    - conf

- name: bashrc extensions
  copy: dest="{{ ansible_env.HOME }}/.config/bash" src=bashrc.d/ backup=yes
  tags:
    - conf

- name: bash_profile
  copy: dest="{{ ansible_env.HOME }}/.bash_profile" src=bash_profile backup=yes
  tags:
    - conf

# https://docs.python.org/3.6/library/site.html
# https://docs.python.org/2.7/library/site.html
- name: python site-packages directory
  file: dest="{{ ansible_env.HOME }}/Library/Python/{{ item }}/lib/python/site-packages" state=directory
  when: ansible_os_family == 'Darwin'
  loop:
    - '2.7'
    - '3.6'
  tags:
    - conf
    - python

- name: python site-packages configuration
  copy: dest="{{ ansible_env.HOME }}/Library/Python/{{ item }}/lib/python/site-packages/homebrew.pth" src=homebrew.pth
  when: ansible_os_family == 'Darwin'
  loop:
    - '2.7'
    - '3.6'
  tags:
    - conf
    - python

- name: create user font directory
  file: dest="{{ user_font_dir }}" state=directory
  tags:
    - conf

- name: install patched Inconsolata
  copy: dest="{{ user_font_dir }}/Inconsolata for Powerline.otf" src="fonts/Inconsolata/Inconsolata for Powerline.otf"

- name: install go fonts
  copy: dest="{{ user_font_dir }}" src="fonts/go/"

- import_tasks: git.yml
  tags:
    - git
    - conf

- import_tasks: golang.yml
  tags:
    - packages
    - golang

- import_tasks: proto.yml
  tags:
    - packages
    - proto

- import_tasks: gcloud.yml
  tags:
    - packages
    - gcloud

# sourcetree

# chrome
# firefox
# firebug
# balsamiq
