---
- name: install packages
  homebrew: name={{ item }} state=latest
  with_items:
    - caskroom/cask/brew-cask
    - vim
    - python
    - git
    - mercurial
    - boot2docker
    - docker-machine
    - docker-compose
    - nodejs
    - dash
    - tmux
    - reattach-to-user-namespace
    - jq
  when: ansible_distribution == 'MacOSX'
  tags:
    - packages

- name: install packages
  homebrew_cask: name={{ item }} state=latest
  with_items:
    - iterm2
    - slack
  tags:
    - packages

- name: global npm packages
  npm: name={{ item }} global=true production=true state=latest
  with_items:
    - coffee-script
    - bower
    - grunt-cli
  tags:
    - packages

- name: install pip packages
  pip: name={{ item }} state=latest
  with_items:
    - awscli
  tags:
    - packages

- name: tmux-config
  copy: dest=~/.tmux.conf src=tmux.conf backup=yes

- name: tmux-osx.conf
  copy: dest=~/.tmux-osx.conf src=tmux-osx.conf backup=yes
  when: ansible_distribution == 'MacOSX'

- name: bashrc
  copy: dest=~/.bashrc src=bashrc backup=yes

- name: bashrc-osx
  copy: dest=~/.bashrc-osx src=bashrc-osx backup=yes
  when: ansible_distribution == 'MacOSX'

- name: bash_profile
  copy: dest=~/.bash_profile src=bash_profile backup=yes

# https://docs.python.org/2/library/site.html
- name: python site-packages directory
  file: dest="{{ ansible_env.HOME }}/Library/Python/2.7/lib/python/site-packages" state=directory

- name: python site-packages configuration
  copy: dest=~/Library/Python/2.7/lib/python/site-packages/homebrew.pth src=homebrew.pth
  when: ansible_distribution == 'MacOSX'

- name: create global git config directory
  file: dest="{{ ansible_env.HOME }}/.config/git" state=directory

- name: create global git ignore file
  copy: src=gitignore dest="{{ ansible_env.HOME }}/.config/git/ignore" force=yes backup=no

- name: global git config file exists
  copy: content= dest="{{ ansible_env.HOME }}/.config/git/config" backup=yes force=no

- name: git doglog alias
  command: git config --global alias.doglog 'log --decorate --oneline --graph'

- name: git config serve alias
  command: git config --global alias.serve 'daemon --reuseaddr --verbose --base-path=. --export-all ./.git'

- name: git config core.editor
  command: git config --global core.editor vim

- name: git config color.ui
  command: git config --global color.ui auto

- name: git config insteadOf https://github.com/
  command: git config --global url.git@github.com:.insteadOf https://github.com/

- name: git config push.default
  command: git config --global push.default simple

# pip install awscli
# git
# mercurial
# nodejs
# boot2docker
# bower
# git config core.excludesfile
# git core.excludesfile
# ~/.bashrc
# ~/.bash_profile
# iTerm2
# slack

# nginx --with-debug
# virtualbox
# docker
# ~/.gitignore
# sourcetree
# colloquy
# hipchat
# go
# chrome
# firefox
# firebug
# balsamiq
# IntelliJ
