- name: add homebrew taps
  homebrew_tap: tap="{{ item }}" state=present
  with_items:
    - caskroom/cask

- name: install packages
  homebrew: name="{{ item }}" state=latest
  with_items:
    - vim
    - tmux
    - git
    - git-lfs
    - git-crypt
    - mercurial
    - python
    - nodejs
    - dash
    - reattach-to-user-namespace
    - jq
    - docker-machine
    - docker-compose
    - ctags
    - direnv
    - tree
  tags:
    - packages

- name: install packages
  homebrew_cask: name="{{ item }}" state=present
  with_items:
    - docker
    - iterm2
    - slack
  tags:
    - packages
