---
- name: taps
  community.general.homebrew_tap:
    name: hashicorp/tap
    state: present

- name: install packages
  homebrew:
    name:
      - autoconf
      - automake
      - tmux
      - git
      - git-lfs
      - git-crypt
      - python3
      - nodejs
      - dash
      - jq
      - universal-ctags
      - direnv
      - ffmpeg
      - graphviz
      - the_silver_searcher
      - hashicorp/tap/Packer
      - minikube
      - awscli
      - int128/kubelogin/kubelogin
      - claude-code
    state: latest
  tags:
    - packages

- name: install maybe managed casks
  homebrew_cask:
    name:
      - 1password-cli
      - docker
      - iterm2
      - slack
      - visual-studio-code
      - wireshark
    state: latest
  ignore_errors: true
  tags:
    - packages
