---
- name: taps
  community.general.homebrew_tap:
    name: hashicorp/tap
    state: present

- name: install packages
  homebrew:
    name:
      - autoconf
      - automake
      - tmux
      - git
      - git-lfs
      - git-crypt
      - mercurial
      - python
      - python3
      - nodejs
      - dash
      - reattach-to-user-namespace
      - jq
      - docker-machine
      - docker-compose
      - ctags
      - direnv
      - ffmpeg
      - graphviz
      - wireshark
      - the_silver_searcher
      - hashicorp/tap/Packer
      - minikube
    state: latest
  tags:
    - packages

- name: install packages
  homebrew_cask:
    name:
      - docker
      - iterm2
      - slack
      - wireshark
    state: latest
  ignore_errors: true
  tags:
    - packages

- name: install hyperkit
  get_url:
    url: https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/docker-machine-driver-hyperkit
    dest: /usr/local/bin/docker-machine-driver-hyperkit
    checksum: "{{ minikube_checksum }}"
  ignore_errors: true
  tags:
    - packages
  become: true

# it shouldn't be necessary to do this, but the mode doesn't get set correctly when attempting to use the mode on the get_url task.
- name: set hyperkit perms
  file:
    path: /usr/local/bin/docker-machine-driver-hyperkit
    mode: 4755
    owner: root
    group: admin
  become: true
