---
- name: docker apt key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg id=0EBFCD88 state=present
  become: yes

- name: docker apt repository
  apt_repository: filename=docker repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable" state=present
  become: yes

- name: chrome apt key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub id=A040830F7FAC5991 state=present
  become: yes

- name: chrome apt repository
  apt_repository: filename=google-chrome repo="deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
  become: yes

#- name: git-lfs apt key
#  apt_key: url=https://packagecloud.io/github/git-lfs/gpgkey state=present
#  become: yes
#
#- name: git-lfs apt repository
#  apt_repository: filename=github_git-lfs repo="deb https://packagecloud.io/github/git-lfs/{{ ansible_lsb.id | lower }}/ {{ ansible_lsb.codename }} main"
#  become: yes
#
#- name: git-lfs src apt repository
#  apt_repository: filename=github_git-lfs repo="deb-src https://packagecloud.io/github/git-lfs/{{ ansible_lsb.id | lower }}/ {{ ansible_lsb.codename }} main"
#  become: yes

- name: install packages
  apt: name="{{ item }}" state=latest update_cache=yes
  become: yes
  with_items:
    - python
    - python-pip
    - git
#   - git-lfs
    - mercurial
    - nodejs
    - npm
    - dash
    - tmux
    - jq
    - docker.io # once docker-ce is suported on zesty, use docker-ce instead
    - google-chrome-stable
    - direnv
    - ffmpeg
    - graphviz
    - silversearcher-ag
  tags:
    - packages

#- name: install packages
#  homebrew_cask: name="{{ item }}" state=present
#  with_items:
#    - slack
#  tags:
#    - packages
