---
- name: check protoc
  shell: command -v protoc
  ignore_errors: yes
  register: protoc_check

- name: protoc version check
  command: protoc --version
  when: protoc_check.rc == 0
  register: installed_protoc_version

- include: install-proto.yml
  when: protoc_check.rc != 0 or installed_protoc_version.stdout.find('libprotoc {{ protoc_version }}') != 0

- name: install Go protoc plugin
  command: go get -u github.com/golang/protobuf/{{ item }}
  #environment:
          # GOPATH: "{{ansible_env.GOPATH}}"
  with_items:
    - proto
    - protoc-gen-go
