---
- name: reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: restart igate
  systemd:
    name: igate
    state: restarted
  become: yes

- name: restart aprs
  systemd:
    name: aprs
    state: restarted
  become: yes
