---
- name: reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: restart igate
  systemd:
    name: igate
    state: restarted
  become: yes

- name: restart sdr-igate
  systemd:
    name: sdr-igate
    state: restarted
  become: yes

- name: restart sdr-aprs
  systemd:
    name: sdr-aprs
    state: restarted
  become: yes

- name: restart fluent-bit
  systemd:
    name: fluent-bit
    state: restarted
  become: yes
