---
# file: base.yml
- hosts: all
  tasks:
    - group_by: key=os_{{ ansible_system }}
  tags:
    - always

- hosts: os_Darwin
  gather_facts: False
  tasks: 
    - name: install Homebrew
      command: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
      args:
        creates: "{{ homebrew_prefix[ansible_architecture] }}/bin/brew"
      tags:
        - packages

    - name: update homebrew
      homebrew: update_homebrew=yes
      tags:
        - packages

- hosts: all
  roles:
    - base
