---
# file: site.yml
- import_playbook: base.yml
  tags:
    - base

- name: update Pis
  hosts: pi
  become: true
  roles:
    - pi
  tags:
    - pi

- name: media
  hosts: filecabinet
  roles:
    - media-server
    - file-server
    - role: educator
      tags:
        - educator
        - education
  tags:
    - media

- name: ham
  hosts: ham
  roles:
    - ham
    - role: aprs-igate
      tags:
        - aprs-igate
  tags:
    - ham

- name: pitft
  hosts: pitft
  roles:
    - pitft
  tags:
    - pitft

- name: flight-tracker
  hosts: flight_tracker
  roles:
    - flight-tracker
  tags:
    - flight-tracker
