---
# file: site.yml
- import_playbook: base.yml
  tags:
    - base

- name: update Pis
  hosts: pi
  become: true
  roles:
    - pi
  tags:
    - pi

- name: media
  hosts: filecabinet
  roles:
    - media-server
    - file-server
  tags:
    - media
