---
- name: reload udev rules
  ansible.builtin.command:
    argv:
      - udevadm
      - control
      - --reload-rules
  become: yes

- name: resync udev
  ansible.builtin.command:
    argv:
      - udevadm
      - trigger
      - --action=change
  become: yes
