# set options
# Use a vi-style line editing interface.  By default, Bash is in emacs mode;
# Use vi mode instead.
#set -o vi
# indicate the mode in the prompt. This option was introduced in Bash 4.3; it
# will have no affect on older versions of Bash. Version 4.3 and later, though,
# will show a '+' to the very left of the prompt in edit mode and a ':' in
# command mode.
#set show-mode-in-prompt on

#if [ -f $(brew --prefix)/etc/bash_completion.d/go-completion.bash ]; then
#	source $(brew --prefix)/etc/bash_completion.d/go-completion.bash
#fi

HISTTIMEFORMAT='%F %T '
HISTFILESIZE=               # allow ~/.bash_history to grow without bound
HISTSIZE=                   # keep all commands in history
HISTCONTROL=ignoreboth      # store neither commands that begin with a space nor more than one copy of repeated commands
HISTIGNORE=?:??             # ignore one and two letter commands
shopt -s histappend                # append to history, don't overwrite it
PROMPT_COMMAND="history -a" # append to history at each shell prompt

if ! command -v __git_ps1 > /dev/null 2>&1
then
	function __git_ps1() { : ; }
fi

nonprintablestart='\001'
nonprintableend='\002'
bold="$(tput bold)"
green="$(tput setaf 2)"
reset="$(tput sgr0)"

# the right pointing brackets are U+276F
# set PS1 so PS1 will be set even when the default __git_ps1 implementation
# (which does nothing to set PS1 as git's __git_ps1 does) is used.
PS1="╭─\u@\h:\w\n╰─${nonprintablestart}${bold}${green}${nonprintableend}❯❯❯${nonprintablestart}${reset}${nonprintableend} "
# use __git_ps1 in PROMPT_COMMAND instead of in PS1 so that GITSHOWCOLORHINTS
# will be honored.
PROMPT_COMMAND=$PROMPT_COMMAND';__git_ps1 "╭─\u@\h:\w" "\n╰─${nonprintablestart}${bold}${green}${nonprintableend}❯❯❯${nonprintablestart}${reset}${nonprintableend} "'
#PROMPT_COMMAND=$PROMPT_COMMAND';__git_ps1 "╭─\u@\h:\w" "\n╰─\[\e[32;1m\]❯❯❯\[\e[0m\] "'

export CLICOLOR=1

export VISUAL=vim
export EDITOR=vim

: ${ORIG_PATH:=${PATH}}
export ORIG_PATH

CPU=$(uname -p)
PATH="/usr/local/bin:$ORIG_PATH"
if [[ "$CPU" == "arm" ]]; then
    PATH="/opt/homebrew/bin:$PATH"
fi

for FILE in $(find -s $HOME/.config/bash -mindepth 1 -maxdepth 1 -type f -not -name 'os_*')
do
	source "$FILE"
done

for OS_FILE in $(find -s $HOME/.config/bash -mindepth 1 -maxdepth 1 -type f -name 'os_'$(uname -s)'*'); do
	source "$OS_FILE"
done

eval "$(direnv hook bash)"
