---
usb_audio_device: "/devices/platform/axi/1000120000.pcie/1f00200000.usb/xhci-hcd.0/usb1/1-1/1-1:1.0/sound/card?"
pitft:
  display: "35r"
  rotation: "270"
  type: console
  #type: fbcp
logforwarding:
  collector:
    host: logs.k7bcx.com
    port: "443"
  shared_key: "{{ vault_igate_fluent_shared_key }}"
