---
golang_version: "1.18.4"
golang_checksums:
  arm64:
    Darwin: "sha256:04eed623d5143ffa44965b618b509e0beccccfd3a4a1bfebc0cdbcf906046769"
    Linux: "sha256:35014d92b50d97da41dade965df7ebeb9a715da600206aa59ce1b2d05527421f"
  x86_64:
    Darwin: "sha256:315e1a2b21a827c68da1b7f492b5dcbe81d8df8a79ebe50922df9588893f87f0"
    Linux: "sha256:c9b099b68d93f5c5c8a8844a89f8db07eaa58270e3a1e01804f17f4cf8df02f5"
golang_pkg: "go{{ golang_version }}.{{ ansible_system | lower }}-{{ pkg_arch }}.tar.gz"
protoc_version: "3.15.6"
protoc_os: "{{ ansible_system | lower }}"
protoc_pkg:
  arm64:
    Darwin: protoc-{{ protoc_version }}-osx-x86_64.zip
    Linux: protoc-{{ protoc_version }}-{{ protoc_os }}-aarch64.zip
  x86_64:
    Darwin: protoc-{{ protoc_version }}-osx-x86_64.zip
    Linux: protoc-{{ protoc_version }}-{{ protoc_os }}-x86_64.zip
protoc_checksums:
  arm64:
    Linux: 38a2f024a0ce68897b1868c59b613939bd41f16c0c8d8890843eccdbbf46ab00
    Darwin: ca025c889efbe02f390b251c153c752a05fb04f5ac8c93929f8dba2818a5392a
  x86_64:
    Linux: 38a2f024a0ce68897b1868c59b613939bd41f16c0c8d8890843eccdbbf46ab00
    Darwin: ca025c889efbe02f390b251c153c752a05fb04f5ac8c93929f8dba2818a5392a
npm_become: no
pip_become: no
user_font_dir: "{{ ansible_env.HOME }}/.fonts"
gcloud_install_path: "{{ ansible_env.HOME }}"
gcloud_version: "365.0.1"
gcloud_checksums:
  arm64:
    Darwin: "sha256:636591e597730649011f510fc8c78e2b133ef8b417992f8d923a87a528dc6d5e"
    Linux: "sha256:fbe88d385e2648ac21bd67586c669e824160424627ac2f9c3fd17c79c765286b"
  x86_64:
    Darwin: "sha256:4ae8a3274eb9b6fca5761ef2eed713bc3486256d11268575febe3351e9e4d902"
    Linux: "sha256:17003cdba67a868c2518ac16efa60dc6175533b7a9fb87304459784308e30fb0"
gcloud_pkg:
  arm64:
    "google-cloud-sdk-{{ gcloud_version }}-{{ ansible_system | lower }}-arm.tar.gz"
  x86_64:
    "google-cloud-sdk-{{ gcloud_version }}-{{ ansible_system | lower }}-x86_64.tar.gz"
minikube_version: v0.25.2
minikube_checksum: sha256:f108e0125e45297f74b34e0dfd1a8e015220305832d437507afc20250f8f6ea5

insteadOfs:
  - base: "git@github.com:"
    urls:
      - git://github.com/
      - "github:"
      - https://github.com/

workspaces:
  - name: do
    gitdir: "~/src/do/"
    email: bcleek@digitalocean.com
    insteadOfs:
      - base: "git@github.internal.digitalocean.com:"
        urls:
          - git://github.internal.digitalocean.com/
          - "ghe:"
          - https://github.internal.digitalocean.com/
          - http://github.internal.digitalocean.com/
