---
golang_version: "1.24.1"
golang_checksums:
  arm64:
    Darwin: "sha256:295581b5619acc92f5106e5bcb05c51869337eb19742fdfa6c8346c18e78ff88"
    Linux: "sha256:8df5750ffc0281017fb6070fba450f5d22b600a02081dceef47966ffaf36a3af"
  x86_64:
    Darwin: "sha256:addbfce2056744962e2d7436313ab93486660cf7a2e066d171b9d6f2da7c7abe"
    Linux: "sha256:cb2396bae64183cdccf81a9a6df0aea3bce9511fc21469fb89a0c00470088073"
golang_pkg: "go{{ golang_version }}.{{ ansible_system | lower }}-{{ pkg_arch }}.tar.gz"
protoc_version: "3.15.6"
protoc_os: "{{ ansible_system | lower }}"
protoc_pkg:
  arm64:
    Darwin: protoc-{{ protoc_version }}-osx-x86_64.zip
    Linux: protoc-{{ protoc_version }}-{{ protoc_os }}-aarch64.zip
  x86_64:
    Darwin: protoc-{{ protoc_version }}-osx-x86_64.zip
    Linux: protoc-{{ protoc_version }}-{{ protoc_os }}-x86_64.zip
protoc_checksums:
  arm64:
    Linux: sha256:38a2f024a0ce68897b1868c59b613939bd41f16c0c8d8890843eccdbbf46ab00
    Darwin: sha256:ca025c889efbe02f390b251c153c752a05fb04f5ac8c93929f8dba2818a5392a
  x86_64:
    Linux: sha256:38a2f024a0ce68897b1868c59b613939bd41f16c0c8d8890843eccdbbf46ab00
    Darwin: sha256:ca025c889efbe02f390b251c153c752a05fb04f5ac8c93929f8dba2818a5392a
npm_become: no
pip_become: no
user_font_dir: "{{ ansible_env.HOME }}/.fonts"
gcloud_install_path: "{{ ansible_env.HOME }}"
gcloud_version: "365.0.1"
gcloud_checksums:
  arm64:
    Darwin: "sha256:636591e597730649011f510fc8c78e2b133ef8b417992f8d923a87a528dc6d5e"
    Linux: "sha256:fbe88d385e2648ac21bd67586c669e824160424627ac2f9c3fd17c79c765286b"
  x86_64:
    Darwin: "sha256:4ae8a3274eb9b6fca5761ef2eed713bc3486256d11268575febe3351e9e4d902"
    Linux: "sha256:17003cdba67a868c2518ac16efa60dc6175533b7a9fb87304459784308e30fb0"
gcloud_pkg:
  arm64:
    "google-cloud-sdk-{{ gcloud_version }}-{{ ansible_system | lower }}-arm.tar.gz"
  x86_64:
    "google-cloud-sdk-{{ gcloud_version }}-{{ ansible_system | lower }}-x86_64.tar.gz"
minikube_version: v0.25.2
minikube_checksum: sha256:f108e0125e45297f74b34e0dfd1a8e015220305832d437507afc20250f8f6ea5

insteadOfs:
  - base: "git@github.com:"
    urls:
      - git://github.com/
      - "github:"
      - https://github.com/
  - base: "git@gist.github.com:"
    urls:
      - git://gist.github.com/
      - "gist:"
      - https://gist.github.com/

workspaces:
  - name: work
    gitdir: "~/src/work/"
    email: billie.cleek@lambdal.com
    insteadOfs: []
    #  - base: "git@github.internal.example.com:"
    #    urls:
    #      - git://github.internal.example.com/
    #      - "ghe:"
    #      - https://github.internal.example.com/
    #      - http://github.internal.example.com/
  - name: personal
    gitdir: "~/src/personal/"
    email: bhcleek@gmail.com
    insteadOfs: []
