---
golang_version: "1.12.8"
golang_checksums:
  Darwin: "sha256:609c8d4913944c0836b0bb291de840dfa2cd45c733b1e50af7a18b1c00bc78f8"
  Linux: "sha256:bd26cd4962a362ed3c11835bca32c2e131c2ae050304f2c4df9fa6ded8db85d2"
golang_pkg: "go{{ golang_version }}.{{ ansible_system | lower }}-amd64.tar.gz"
protoc_version: "3.2.0"
protoc_os: "{{ ansible_system | lower }}"
protoc_pkg: protoc-{{ protoc_version }}-{{ protoc_os }}-x86_64.zip
protoc_checksums:
  Linux: 9cf9a8661d649b8477fe0ad32a8b28d351a170a62e210bf848d90a29f1f4df9d
  Darwin: 69fbd04599c53af7826f9a6cf2a34f15aec6e0800c24cd572f4f5ba9e156a2cb
npm_become: no
pip_become: no
user_font_dir: "{{ ansible_env.HOME }}/.fonts"
gcloud_install_path: "{{ ansible_env.HOME }}"
gcloud_version: "183.0.0"
gcloud_checksums:
  Darwin: "sha256:605332cb305a04d377572d61063db88433862521f1aa4887d3b3fbfaaf1519a2"
  Linux: "sha256:6e5c76999ff3f14621d26e3c76967dc4c43613344947ab42fcc764311642c898"
gcloud_pkg: "google-cloud-sdk-{{ gcloud_version }}-{{ ansible_system | lower }}-x86_64.tar.gz"
minikube_version: v0.25.2
minikube_checksum: sha256:f108e0125e45297f74b34e0dfd1a8e015220305832d437507afc20250f8f6ea5

insteadOfs:
  - base: "git@github.com:"
    urls:
      - git://github.com/
      - "github:"
      - https://github.com/

workspaces:
  - name: do
    gitdir: "~/src/do/"
    email: bcleek@digitalocean.com
    insteadOfs:
      - base: "git@github.internal.digitalocean.com:"
        urls:
          - git://github.internal.digitalocean.com/
          - "ghe:"
          - https://github.internal.digitalocean.com/
          - http://github.internal.digitalocean.com/
