---
golang_version: "1.27.0"
golang_checksums:
  arm64:
    Darwin: "sha256:90493b3bbd5e10f91d12153198bf1994fd756399b4fec93b49b0c6e2acdeeb3e"
    Linux: "sha256:51798d2c42d0e1c6ed7fd9f48728b4193abac9e8aad6dbac2fe96a81f5909bda"
  x86_64:
    Darwin: "sha256:d3314e25496e4381d71a5c51d2907e7af655d199f6780b549f015bd85fef4986"
    Linux: "sha256:675c26c449cbb18fc24b74650de1eabbae6e16f64326fd85a283fb3b58280685"
golang_pkg: "go{{ golang_version }}.{{ ansible_facts['system'] | lower }}-{{ pkg_arch }}.tar.gz"
protoc_version: "3.15.6"
protoc_os: "{{ ansible_facts['system'] | lower }}"
protoc_pkg:
  arm64:
    Darwin: protoc-{{ protoc_version }}-osx-x86_64.zip
    Linux: protoc-{{ protoc_version }}-{{ protoc_os }}-aarch64.zip
  x86_64:
    Darwin: protoc-{{ protoc_version }}-osx-x86_64.zip
    Linux: protoc-{{ protoc_version }}-{{ protoc_os }}-x86_64.zip
protoc_checksums:
  arm64:
    Linux: sha256:38a2f024a0ce68897b1868c59b613939bd41f16c0c8d8890843eccdbbf46ab00
    Darwin: sha256:ca025c889efbe02f390b251c153c752a05fb04f5ac8c93929f8dba2818a5392a
  x86_64:
    Linux: sha256:38a2f024a0ce68897b1868c59b613939bd41f16c0c8d8890843eccdbbf46ab00
    Darwin: sha256:ca025c889efbe02f390b251c153c752a05fb04f5ac8c93929f8dba2818a5392a
npm_become: no
pip_become: no
user_font_dir: "{{ ansible_facts['env']['HOME'] }}/.fonts"
gcloud_install_path: "{{ ansible_facts['env']['HOME'] }}"
gcloud_version: "560.0.0"
gcloud_checksums:
  arm64:
    Darwin: "sha256:5374eea1b294eb2455ef849b797003a96190fbd688e2262e1a8fbf7046250d1f"
    Linux: "sha256:5560c93c62eec321776bd0cafafe3fbce673b69f4c010836dffe40322fa2aebe"
  x86_64:
    Darwin: "sha256:203e9e015cda82fe589273548b4c4e509a6c66a1bcc0a6df2f637a569df4f6d9"
    Linux: "sha256:4ee13c74063894c859bfe77455c0c728303267f4d3650148f26d509b721e5022"
gcloud_pkg:
  arm64:
    "google-cloud-cli-{{ gcloud_version }}-{{ ansible_facts['system'] | lower }}-arm.tar.gz"
  x86_64:
    "google-cloud-cli-{{ gcloud_version }}-{{ ansible_facts['system'] | lower }}-x86_64.tar.gz"

insteadOfs:
  - base: "git@github.com:"
    urls:
      - git://github.com/
      - "github:"
      - https://github.com/
  - base: "git@gist.github.com:"
    urls:
      - git://gist.github.com/
      - "gist:"
      - https://gist.github.com/

workspaces:
  - name: work
    gitdir: "~/src/work/"
    email: billie.cleek@lambdal.com
    insteadOfs: []
    #  - base: "git@github.internal.example.com:"
    #    urls:
    #      - git://github.internal.example.com/
    #      - "ghe:"
    #      - https://github.internal.example.com/
    #      - http://github.internal.example.com/
  - name: personal
    gitdir: "~/src/personal/"
    email: bhcleek@gmail.com
    insteadOfs: []
