---
- name: package check
  ansible.builtin.package_facts:
    manager: auto

- name: get piaware repo deb
  ansible.builtin.get_url:
    dest: "{{ansible_env.HOME}}/{{piaware_repository.deb}}"
    url: https://flightaware.com/adsb/piaware/files/packages/pool/piaware/f/flightaware-apt-repository/{{piaware_repository.deb}}
  when: ansible_facts.packages['piaware-repository'] is not defined or piaware_repository.version not in (ansible_facts.packages['piaware-repository'] | map(attribute='version' ) | list)

- name: install piaware repo deb
  apt:
    deb: "{{ansible_env.HOME}}/{{piaware_repository.deb}}"
    update_cache: no
  become: yes
  when: ansible_facts.packages['piaware-repository'] is not defined or piaware_repository.version not in (ansible_facts.packages['piaware-repository'] | map(attribute='version' ) | list)

- name: remove piaware repo deb
  file:
    dest: "{{ansible_env.HOME}}/{{piaware_repository.deb}}"
    state: absent
  when: ansible_facts.packages['piaware-repository'] is not defined or piaware_repository.version not in (ansible_facts.packages['piaware-repository'] | map(attribute='version' ) | list)

- name: update cache for piaware
  apt:
    update_cache: yes
  become: yes
  when: ansible_facts.packages['piaware-repository'] is not defined or piaware_repository.version not in (ansible_facts.packages['piaware-repository'] | map(attribute='version' ) | list)

- name: install ADS-B tools
  apt:
    name:
    - piaware
    - dump1090-fa
    - dump978-fa
    update_cache: yes
    cache_valid_time: 86400
    state: latest
  become: yes
  tags:
    - packages
