---
- name: aprs config directory
  file:
    path: /etc/aprs
    state: directory
  become: yes

- name: igate.conf
  template:
    src: igate.conf.tmpl
    dest: /etc/aprs/igate.conf
  notify:
    - restart igate
  become: yes

- name: igate unit
  copy:
    src: igate.service
    dest: /etc/systemd/system/igate.service
  notify:
    - reload systemd
    - restart igate
  become: yes

- name: igate service started
  systemd:
    service: igate
    state: started
  notify:
    - reload systemd
    - restart igate
  become: yes

- name: igate-input.conf
  ansible.builtin.copy:
    src: fluent/igate-input.conf
    dest: /etc/fluent-bit/conf.d/igate-input.conf
  notify:
    - restart fluent-bit
  become: yes
  when: true

- name: igate-filter.conf
  ansible.builtin.copy:
    src: fluent/igate-filter.conf
    dest: /etc/fluent-bit/conf.d/igate-filter.conf
  notify:
    - restart fluent-bit
  become: yes
  when: true

- name: igate-output.conf
  ansible.builtin.template:
    src: fluent/igate-output.conf.tmpl
    dest: /etc/fluent-bit/conf.d/igate-output.conf
  notify:
    - restart fluent-bit
  become: yes
  when: true
