---
- name: aprs config directory
  file:
    path: /etc/aprs
    state: directory
  become: yes

- name: sdr-igate.conf
  template:
    src: sdr-igate.conf.tmpl
    dest: /etc/aprs/sdr-igate.conf
  notify:
   #- restart sdr-igate
  become: yes

- name: sdr-igate.sh
  copy:
    src: sdr-igate.sh
    dest: /usr/local/bin/sdr-igate.sh
    mode: preserve
  notify:
   #- restart sdr-igate
  become: yes

- name: sdr-igate unit
  copy:
    src: sdr-igate.service
    dest: /etc/systemd/system/sdr-igate.service
  notify:
    - reload systemd
   #- restart sdr-igate
  become: yes

- name: sdr-aprs unit
  copy:
    src: sdr-aprs.service
    dest: /etc/systemd/system/sdr-aprs.service
  notify:
    - reload systemd
   #- restart sdr-aprs
  become: yes

- name: sdr-aprs socket
  copy:
    src: sdr-aprs.socket
    dest: /etc/systemd/system/sdr-aprs.socket
  notify:
    - reload systemd
   #- restart sdr-aprs
   #- restart sdr-igate
  become: yes

- name: sdr-igate service started
  systemd:
    service: sdr-igate
    state: stopped
  notify:
    - reload systemd
   #- restart sdr-igate
  become: yes

- name: sdr-aprs service started
  systemd:
    service: sdr-aprs.service
    state: stopped
  notify:
    - reload systemd
   #- restart sdr-aprs
  become: yes
