---
- name: install packages
  apt:
    name:
      - direnv
      - fzf
      - parallel
      - tree
      - vim
      - python3-pip
      - python3-venv
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  become: yes
  tags:
    - packages
