---
- name: install packages
  homebrew:
    state: latest
    name:
      - coreutils
      - direnv
      - fzf
      - gnu-getopt
      - gnu-sed
      - gnu-tar
      - gnu-time
      - parallel
      - tmux
      - tree
      - vim
      - bash
  tags:
    - packages

- name: homebrew bash in /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    insertafter: "EOF"
    line: "{{ homebrew_prefix }}/bin/bash"
  become: yes
