---
- name: install packages
  homebrew:
    state: latest
    name:
      - coreutils
      - direnv
      - fzf
      - gnu-getopt
      - gnu-sed
      - gnu-tar
      - gnu-time
      - parallel
      - tmux
      - tree
      - vim
  tags:
    - packages
